{application,membrane_aac_plugin,
             [{applications,[kernel,stdlib,elixir,membrane_core,bunch,
                             membrane_aac_format,crc]},
              {description,"Membrane Multimedia Framework plugin for AAC"},
              {modules,['Elixir.Membrane.AAC.Filler',
                        'Elixir.Membrane.AAC.Filler.State',
                        'Elixir.Membrane.AAC.Parser',
                        'Elixir.Membrane.AAC.Parser.Helper']},
              {registered,[]},
              {vsn,"0.15.0"}]}.
