{application,membrane_flv_plugin,
             [{applications,[kernel,stdlib,elixir,membrane_core,
                             membrane_aac_format,membrane_mp4_format,
                             membrane_h264_format,bimap,bunch]},
              {description,"FLV Container implementation for Membrane Framework"},
              {modules,['Elixir.Membrane.AVC.Utils','Elixir.Membrane.FLV',
                        'Elixir.Membrane.FLV.Demuxer',
                        'Elixir.Membrane.FLV.Header',
                        'Elixir.Membrane.FLV.Muxer',
                        'Elixir.Membrane.FLV.Packet',
                        'Elixir.Membrane.FLV.Parser',
                        'Elixir.Membrane.FLV.Serializer']},
              {registered,[]},
              {vsn,"0.7.0"}]}.
